<?php

use PHPUnit\Framework\TestCase;

require __DIR__ . "/../../../../api/admin/model/catalog/attibute.php";

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-11-03 at 04:08:53.
 */
class ModelCatalogAttributeTest extends TestCase {

    /**
     * @var ModelCatalogAttribute
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ModelCatalogAttribute;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ModelCatalogAttribute::getAttributes
     * @todo   Implement testGetAttributes().
     */
    public function testGetAttributes() {
        // Remove the following lines when you implement this test.

        $sort = [
            "ad.name" => "name",
            "attribute_group" => 1,
            "a.sort_order" => 1
        ];
        $data = [
            "filter_name" => "name",
            "filter_attribute_group_id" => 1,
            "sort" => $sort,
            "order" => "DESC",
            "start" => -1,
            "limit" => 0
        ];

        $attributes = $this->object->getAttributes($data);
        $this->AssertGreaterThan(0, count($attributes));
    }

}
