<?php

use PHPUnit\Framework\TestCase;

require __DIR__ . "/../../../../api/admin/model/catalog/attribute_group.php";

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-11-03 at 06:37:19.
 */
class ModelCatalogAttributeGroupTest extends TestCase {

    /**
     * @var ModelCatalogAttributeGroup
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ModelCatalogAttributeGroup;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ModelCatalogAttributeGroup::getAttributeGroups
     * @todo   Implement testGetAttributeGroups().
     */
    public function testGetAttributeGroups() {
        // Remove the following lines when you implement this test.
        $sort_data = [
            "agd.name" => "name",
            "ag.sort_order" => "something"
        ];
        $data = [
            "filter_name" => "something_name",
            "filter_attribute_group_id" => 1,
            "sort" => $sort_data,
            "order" => "DESC",
            "start" => -1,
            "limit" => 0
        ];

        $attributeGroups = $this->object->getAttributeGroups($data);
        $this->AssertGreaterThan(0, count($attributeGroups));
    }

}
