<?php

use PHPUnit\Framework\TestCase;

require __DIR__ . "/../../../../api/admin/model/catalog/category.php";

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-10-25 at 22:14:17.
 */
class ModelCatalogCategoryTest extends TestCase {

    /**
     * @var ModelCatalogCategory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ModelCatalogCategory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ModelCatalogCategory::addCategory
     * @todo   Implement testAddCategory().
     */
    public function testAddCategory() {
        // Remove the following lines when you implement this test.
        $data = [
            "image" => "/api/image/catalog/table.jpg",
            "parent_id" => "25",
            "category_description" => "something",
            "category_filter" => "something",
            "category_store" => "something",
            "category_seo_url" => "something",
            "category_layout" => "something",
            "top" => "1",
            "column" => "1",
            "sort_order" => "3",
            "status" => "1",
            "date_added" => "2017-10-29 10:16:14",
            "date_modified" => "2017-10-30 09:10:10"
        ];
        $idresult = $this->object->addCategory($data);
        $this->assertNotNull($this->$idresult);
    }

      
    /**
     * @covers ModelCatalogCategory::getCategories
     * @todo   Implement testGetCategories().
     */
    public function testGetCategories() {
        $data = array();
        $categories = $this->object->getCategories($data);
        $this->assertCount(8, $categories);
    }

  

}
