<?php

use PHPUnit\Framework\TestCase;

require __DIR__ . "/../../../../api/admin/model/localisation/currency.php";

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-11-03 at 06:21:17.
 */
class ModelLocalisationCurrencyTest extends TestCase {

    /**
     * @var ModelLocalisationCurrency
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ModelLocalisationCurrency;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

   

    /**
     * @covers ModelLocalisationCurrency::getCurrencies
     * @todo   Implement testGetCurrencies().
     */
    public function testGetCurrencies() {
        // Remove the following lines when you implement this test.
        $sort_data = [
            "title" => "title",
            "code" => "CO",
            "value" => "something",
            "date_modified" => null
        ];
        $data = [
            "filter_name" => "name",
            "filter_attribute_group_id" => 1,
            "sort" => $sort_data,
            "order" => "DESC",
            "start" => -1,
            "limit" => 0
        ];

        $currencies = $this->object->getCurrencies($data);
        $this->AssertGreaterThan(0, count($currencies));
    }

}
