<?php

use PHPUnit\Framework\TestCase;

require __DIR__ . "/../../../../api/admin/model/customer/customer.php";

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-11-03 at 06:42:54.
 */
class ModelCustomerCustomerTest extends TestCase {

    /**
     * @var ModelCustomerCustomer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ModelCustomerCustomer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ModelCustomerCustomer::getAddress
     * @todo   Implement testGetAddress().
     */
    public function testGetAddress() {
        // Remove the following lines when you implement this test.
        $address_id = 1;
        $order = $this->object->getAddress($address_id);
        $this->assertInternalType('array', $order);
    }

}
