<?php

use PHPUnit\Framework\TestCase;

require __DIR__ . "/../../../../api/admin/model/catalog/filter.php";

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-11-03 at 03:35:28.
 */
class ModelCatalogFilterTest extends TestCase {

    /**
     * @var ModelCatalogFilter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ModelCatalogFilter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

   

    /**
     * @covers ModelCatalogFilter::editFilter
     * @todo   Implement testEditFilter().
     */
    public function testEditFilter() {
        // Remove the following lines when you implement this test.
        $filter_id = 1;
        $data = [
            $filter_id,
            "filter_description" => "something",
            "sort_order" => 3
        ];
        $filter = $this->object->getFilter($filter_id);
        $filter_group_id = 1;
        $this->object->editFilter($filter_group_id, $data);
        $filterUpdate = $this->object->getFilter($filter_id);
        $this->assertNotEquals($filter, $filterUpdate);
    }

  

}
