<?php

use PHPUnit\Framework\TestCase;

require __DIR__ . "/../../../../api/admin/model/localisation/geo-zone.php";

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-11-03 at 06:30:28.
 */
class ModelLocalisationGeoZoneTest extends TestCase {

    /**
     * @var ModelLocalisationGeoZone
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ModelLocalisationGeoZone;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ModelLocalisationGeoZone::getGeoZones
     * @todo   Implement testGetGeoZones().
     */
    public function testGetGeoZones() {
        // Remove the following lines when you implement this test.
         $sort_data = [
            "name" => "something_name",
            "description" => "something_description"
        ];
        $data = [
            "filter_name" => "name",
            "filter_attribute_group_id" => 1,
            "sort" => $sort_data,
            "order" => "DESC",
            "start" => -1,
            "limit" => 0
        ];

        $getGeoZones = $this->object->getGeoZones($data);
        $this->AssertGreaterThan(0, count($getGeoZones));
    }

}
