<?php
use PHPUnit\Framework\TestCase;

require __DIR__ . "/../../../../api/admin/model/catalog/category.php";
/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-10-31 at 21:08:55.
 */
class ModelCatalogInformationTest extends TestCase {

    /**
     * @var ModelCatalogInformation
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ModelCatalogInformation;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ModelCatalogInformation::addInformation
     * @todo   Implement testAddInformation().
     */
    public function testAddInformation() {
        // Remove the following lines when you implement this test.
        $data = [
            "bottom" => "1",
            "sort_order" => "5",
            "status" => "1",
            "status" => "1",
            "information_store" => "something",
            "information_seo_url" => "something",
            "information_layout" => "something"
        ];
        $information_id = $this->object->addInformation($data);
        $this->assertNotNull($this->$information_id);
    }

    /**
     * @covers ModelCatalogInformation::editInformation
     * @todo   Implement testEditInformation().
     */
    public function testEditInformation() {
        // Remove the following lines when you implement this test.
        $information_id = 3;
        $data = [
            "bottom" => "1",
            "sort_order" => "3",
            "status" => "0",//El valor a editar
            "status" => "1",
            "information_store" => "something",
            "information_seo_url" => "something",
            "information_layout" => "something"
        ];
        $this->object->editInformation($information_id,$data);
        $this->assertEquals($data, $this->object->getInformation($information_id));
    }

   
    

    /**
     * @covers ModelCatalogInformation::getInformations
     * @todo   Implement testGetInformations().
     */
    public function testGetInformations() {
        // Remove the following lines when you implement this test.
        $data = array();
        $informations = $this->object->getInformations($data);
        $this->assertCount(4, $informations);
    }

   

}
