<?php
use PHPUnit\Framework\TestCase;

require __DIR__ . "/../../../../api/admin/model/catalog/category.php";
/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-10-31 at 21:08:28.
 */
class ModelCatalogOptionTest extends TestCase {

    /**
     * @var ModelCatalogOption
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ModelCatalogOption;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ModelCatalogOption::addOption
     * @todo   Implement testAddOption().
     */
    public function testAddOption() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    /**
     * @covers ModelCatalogOption::getOptions
     * @todo   Implement testGetOptions().
     */
    public function testGetOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

   

}
