<?php
use PHPUnit\Framework\TestCase;

require __DIR__ . "/../../../../api/admin/model/catalog/category.php";
/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-10-31 at 21:08:28.
 */
class ModelCatalogOptionTest extends TestCase {

    /**
     * @var ModelCatalogOption
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ModelCatalogOption;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ModelCatalogOption::addOption
     * @todo   Implement testAddOption().
     */
    public function testAddOption() {
        // Remove the following lines when you implement this test.
         $data = [
            "option_description" => "something",
            "option_value" => 1,
            "option_value_description" => null
        ];
        $option_id = $this->object->addOption($data);
        $this->assertNotNull($this->$option_id);
    }


    /**
     * @covers ModelCatalogOption::getOptions
     * @todo   Implement testGetOptions().
     */
    public function testGetOptions() {
        // Remove the following lines when you implement this test.
        
        $sort_data = [
            "od.name" => "name",
            "o.type" => "something_type",
            "o.sort_order" => 1
        ];
        $data = [
            "filter_name" => "name",
            "filter_attribute_group_id" => 1,
            "sort" => $sort_data,
            "order" => "DESC",
            "start" => -1,
            "limit" => 0
        ];

        $options = $this->object->getOptions($data);
        $this->AssertGreaterThan(0, count($options));
    }

   

}
